### ISSUE TITLE
[Bug] out dated dependency 

### ISSUE THREAD

**Issue by Deselikem** [skills/continuous-integration#9]
**Describe the bug**
There is an error when running ` npm install remark-cli remark-preset-lint-consistent `

![image](https://user-images.githubusercontent.com/91301618/175648206-f39767fa-b14c-4762-84db-7fce01ef13c9.png)

**Comment by sinsukehlab** [comment]
I cannot get what you mean by "outdated dependency".
It says, "found 0 vulnerabilities", so the error is not due to vulnerabilities.
Course makers expect the workflow to create a error build. You will fix this in Step 2.
The <font color="yellow">warning</font> message will help you to fix the error.

**Comment by heiskr** [comment]
Thank you for the issue. I believe Actions runners have been updated to no longer include this deprecation message, but let us know if you still see the deprecation message.
